### ISSUE TITLE
Relax pending order creation 

### ISSUE THREAD

**Issue by ashkan18** [artsy/exchange#47]
follow up on discussion: https://artsy.slack.com/archives/CB110C6LE/p1530118511000348

**Comment by ashkan18** [comment]
# Current State
When creating an order by a user, we check if this user has any existing pending order for this artwork/editionset and if they do we raise a validation error and don't allow creating a new order for the same artwork. In current state a user can have multiple pending orders for different artworks at a time.

# Proposed Change
A user can have only one _pending_ order at a time. When user tries to create a new order, we check if they have any pending order, we abandon their existing pending order and then we create a new one.

**Comment by joeyAghion** [comment]
This proposal sounds like it would support v0 well. It's worth keeping in mind how implementations may need to change to support line item quantities of >1, or in the further future when multiple items [from the same partner, probably] can be in a single order.

If clients invoke a "createOrder" mutation, that should presumably continue to create a _new_ order. If quantities >1 are to be supported, the affordance offered to buyers should maybe change to behave more like an "addToCart," where by default it starts an order with that item, but if the item is already in the pending order it increments the item's quantity. Deployed clients (like Eigen) might continue to invoke the "createOrder" operation and it could continue to work the old way.

If orders must be associated with a single partner and we switch to more of a "cart" behavior, we'll need to handle the case when a pending order exists but can't be added to, because it's associated with a different partner. At that point we either need to abandon the existing one or support multiple pending orders. We can leave that decision for later, and can depend on optional params (like `usePendingOrder=[if_possible|never]`) to ease any transition.

**Comment by starsirius** [comment]
I like to think about a pending order as a shopping cart in the existing e-commerce site experience as Amazon. It makes sense to me there is no clear use case, at least for the pilot, to support multiple pending orders per user (even on different works). It's also a familiar mental model/good UX for buyers.

The only case I can think of right now is, as @joeyAghion mentioned, if we don't allow checking out the same order with multiple partners, and agreed that we can worry about that later. I believe there is room for product to develop the features and experiences. FWIW, on the actual payment side, Stripe supports (in public beta) [creating separate charges and transfers](https://stripe.com/docs/connect/charges-transfers).
